export const ACCOMODATION_LIST_REQUEST = 'ACCOMODATION_LIST_REQUEST'
export const ACCOMODATION_LIST_SUCCESS = 'ACCOMODATION_LIST_SUCCESS'
export const ACCOMODATION_LIST_FAIL = 'ACCOMODATION_LIST_FAIL'



export const ROOM_LIST_REQUEST = 'ROOM_LIST_REQUEST'
export const ROOM_LIST_SUCCESS = 'ROOM_LIST_SUCCESS'
export const ROOM_LIST_FAIL = 'ROOM_LIST_FAIL'

export const MAINTENANCE_UPDATE_REQUEST = 'MAINTENANCE_UPDATE_REQUEST'
export const MAINTENANCE_UPDATE_SUCCESS = 'MAINTENANCE_UPDATE_SUCCESS'
export const MAINTENANCE_UPDATE_FAIL = 'MAINTENANCE_UPDATE_FAIL'


export const IMAGE_REMOVE_REQUEST = 'IMAGE_REMOVE_REQUEST'
export const IMAGE_REMOVE_SUCCESS = 'IMAGE_REMOVE_SUCCESS'
export const IMAGE_REMOVE_FAIL = 'IMAGE_REMOVE_FAIL'


export const HOSTEL_LIST_REQUEST = 'HOSTEL_LIST_REQUEST'
export const HOSTEL_LIST_SUCCESS = 'HOSTEL_LIST_SUCCESS'
export const HOSTEL_LIST_FAIL = 'HOSTEL_LIST_FAIL'


export const HOSTEL_DETAILS_REQUEST = 'HOSTEL_DETAILS_REQUEST'
export const HOSTEL_DETAILS_SUCCESS = 'HOSTEL_DETAILS_SUCCESS'
export const HOSTEL_DETAILS_FAIL = 'HOSTEL_DETAILS_FAIL'


export const ROOM_DETAILS_REQUEST = 'ROOM_DETAILS_REQUEST'
export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS'
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL'

export const ACCOMODATION_DETAILS_REQUEST = 'ACCOMODATION_DETAILS_REQUEST'
export const ACCOMODATION_DETAILS_SUCCESS = 'ACCOMODATION_DETAILS_SUCCESS'
export const ACCOMODATION_DETAILS_FAIL = 'ACCOMODATION_DETAILS_FAIL'


export const MAINTENANCE_DETAILS_REQUEST = 'MAINTENANCE_DETAILS_REQUEST'
export const MAINTENANCE_DETAILS_SUCCESS = 'MAINTENANCE_DETAILS_SUCCESS'
export const MAINTENANCE_DETAILS_FAIL = 'MAINTENANCE_DETAILS_FAIL'



export const HOSTEL_DELETE_REQUEST = 'HOSTEL_DELETE_REQUEST'
export const HOSTEL_DELETE_SUCCESS = 'HOSTEL_DELETE_SUCCESS'
export const HOSTEL_DELETE_FAIL = 'HOSTEL_DELETE_FAIL'


export const ROOM_DELETE_REQUEST = 'ROOM_DELETE_REQUEST'
export const ROOM_DELETE_SUCCESS = 'ROOM_DELETE_SUCCESS'
export const ROOM_DELETE_FAIL = 'ROOM_DELETE_FAIL'


export const NOTICE_DELETE_REQUEST = 'NOTICE_DELETE_REQUEST'
export const NOTICE_DELETE_SUCCESS = 'NOTICE_DELETE_SUCCESS'
export const NOTICE_DELETE_FAIL = 'NOTICE_DELETE_FAIL'







export const HOSTEL_CREATE_REQUEST = 'HOSTEL_CREATE_REQUEST'
export const HOSTEL_CREATE_SUCCESS = 'HOSTEL_CREATE_SUCCESS'
export const HOSTEL_CREATE_FAIL = 'HOSTEL_CREATE_FAIL'
export const HOSTEL_CREATE_RESET = 'HOSTEL_CREATE_RESET'



export const ROOM_CREATE_REQUEST = 'ROOM_CREATE_REQUEST'
export const ROOM_CREATE_SUCCESS = 'ROOM_CREATE_SUCCESS'
export const ROOM_CREATE_FAIL = 'ROOM_CREATE_FAIL'
export const ROOM_CREATE_RESET = 'ROOM_CREATE_RESET'


export const EDIT_HOSTEL_REQUEST = 'EDIT_HOSTEL_REQUEST'
export const EDIT_HOSTEL_SUCCESS = 'EDIT_HOSTEL_SUCCESS'
export const EDIT_HOSTEL_FAIL = 'EDIT_HOSTEL_FAIL'
export const EDIT_HOSTEL_RESET = 'EDIT_HOSTEL_RESET'



export const EDIT_ROOM_REQUEST = 'EDIT_ROOM_REQUEST'
export const EDIT_ROOM_SUCCESS = 'EDIT_ROOM_SUCCESS'
export const EDIT_ROOM_FAIL = 'EDIT_ROOM_FAIL'
export const EDIT_ROOM_RESET = 'EDIT_ROOM_RESET'



export const MESSSAGE_DELETE_REQUEST = 'MESSSAGE_DELETE_REQUEST'
export const MESSSAGE_DELETE_SUCCESS = 'MESSSAGE_DELETE_SUCCESS'
export const MESSSAGE_DELETE_FAIL = 'MESSSAGE_DELETE_FAIL'
