export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST'
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS'
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL'

export const ACCOMODATION_LIST_REQUEST = 'ACCOMODATION_LIST_REQUEST'
export const ACCOMODATION_LIST_SUCCESS = 'ACCOMODATION_LIST_SUCCESS'
export const ACCOMODATION_LIST_FAIL = 'ACCOMODATION_LIST_FAIL'

export const PAYMENTS_LIST_REQUEST = 'PAYMENTS_LIST_REQUEST'
export const PAYMENTS_LIST_SUCCESS = 'PAYMENTS_LIST_SUCCESS'
export const PAYMENTS_LIST_FAIL = 'PAYMENTS_LIST_FAIL'



export const COMPLAINT_DETAILS_REQUEST = 'COMPLAINT_DETAILS_REQUEST'
export const COMPLAINT_DETAILS_SUCCESS = 'COMPLAINT_DETAILS_SUCCESS'
export const COMPLAINT_DETAILS_FAIL = 'COMPLAINT_DETAILS_FAIL'

export const MAINTENANCE_DETAILS_REQUEST = 'MAINTENANCE_DETAILS_REQUEST'
export const MAINTENANCE_DETAILS_SUCCESS = 'MAINTENANCE_DETAILS_SUCCESS'
export const MAINTENANCE_DETAILS_FAIL = 'MAINTENANCE_DETAILS_FAIL'





export const ACCOMODATION_DETAILS_REQUEST = 'ACCOMODATION_DETAILS_REQUEST'
export const ACCOMODATION_DETAILS_SUCCESS = 'ACCOMODATION_DETAILS_SUCCESS'
export const ACCOMODATION_DETAILS_FAIL = 'ACCOMODATION_DETAILS_FAIL'




export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST'
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS'
export const REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL'

export const ACCOMODATION_CREATE_REQUEST = 'ACCOMODATION_CREATE_REQUEST'
export const ACCOMODATION_CREATE_SUCCESS = 'ACCOMODATION_CREATE_SUCCESS'
export const ACCOMODATION_CREATE_FAIL = 'ACCOMODATION_CREATE_FAIL'
export const ACCOMODATION_CREATE_RESET = 'ACCOMODATION_CREATE_RESET'

export const COMPLAINT_UPDATE_REQUEST = 'COMPLAINT_UPDATE_REQUEST'
export const COMPLAINT_UPDATE_SUCCESS = 'COMPLAINT_UPDATE_SUCCESS'
export const COMPLAINT_UPDATE_FAIL = 'COMPLAINT_UPDATE_FAIL'
export const COMPLAINT_UPDATE_RESET = 'COMPLAINT_UPDATE_RESET'


export const ACCOMODATION_UPDATE_REQUEST = 'ACCOMODATION_UPDATE_REQUEST'
export const ACCOMODATION_UPDATE_SUCCESS = 'ACCOMODATION_UPDATE_SUCCESS'
export const ACCOMODATION_UPDATE_FAIL = 'ACCOMODATION_UPDATE_FAIL'
export const ACCOMODATION_UPDATE_RESET = 'ACCOMODATION_UPDATE_RESET'




export const MAINTENANCE_CREATE_REQUEST = 'MAINTENANCE_CREATE_REQUEST'
export const MAINTENANCE_CREATE_SUCCESS = 'MAINTENANCE_CREATE_SUCCESS'
export const MAINTENANCE_CREATE_FAIL = 'MAINTENANCE_CREATE_FAIL'
export const MAINTENANCE_CREATE_RESET = 'MAINTENANCE_CREATE_RESET'





export const COMPLAINT_CREATE_REQUEST = 'COMPLAINT_CREATE_REQUEST'
export const COMPLAINT_CREATE_SUCCESS = 'COMPLAINT_CREATE_SUCCESS'
export const COMPLAINT_CREATE_FAIL = 'COMPLAINT_CREATE_FAIL' 

export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST'
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS'
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL' 




export const COMPLAINTS_LIST_REQUEST = 'COMPLAINTS_LIST_REQUEST'
export const COMPLAINTS_LIST_SUCCESS = 'COMPLAINTS_LIST_SUCCESS'
export const COMPLAINTS_LIST_FAIL = 'COMPLAINTS_LIST_FAIL' 
export const COMPLAINTS_LIST_RESET = 'COMPLAINTS_LIST_RESET' 


export const MAINRENANCE_LIST_REQUEST = 'MAINRENANCE_LIST_REQUEST'
export const MAINRENANCE_LIST_SUCCESS = 'MAINRENANCE_LIST_SUCCESS'
export const MAINRENANCE_LIST_FAIL = 'MAINRENANCE_LIST_FAIL' 
export const MAINRENANCE_LIST_RESET = 'MAINRENANCE_LIST_RESET'


